CREATE FUNCTION [dbo].[FORNVL_GET_ISNULL](@A SQL_VARIANT, @B SQL_VARIANT )
RETURNS SQL_VARIANT
AS

BEGIN

    DECLARE @TEMP SQL_VARIANT

    IF (@A = NULL)
   SELECT @TEMP = @B
    ELSE
    SELECT @TEMP = @A

     RETURN @TEMP

END