CREATE FUNCTION [dbo].[SFADOCCTG_PALL]
(
      @PCOMP_NO NVARCHAR(40)
    , @DOCCTG_ID BIGINT
	, @DESCRIPTION NVARCHAR(40)
)
RETURNS TABLE 
AS
RETURN(
    WITH DATATABLE AS ( 
        SELECT 
             A.COMP_NO 
           , A.DOCCTG_ID
           , A.P_DOCCTG_ID
           , 1 AS LVL
		   , A.DESCRIPTION
		   , CONVERT(VARCHAR, A.DOCCTG_ID) AS SORT
        FROM TADOCCTG A
        WHERE 1=1
            and COMP_NO  = @PCOMP_NO
            and DOCCTG_ID = CASE @DOCCTG_ID WHEN '' THEN DOCCTG_ID ELSE @DOCCTG_ID END
			and isnull(description,'') like CASE @DOCCTG_ID WHEN '' THEN '%'+@DESCRIPTION+'%' ELSE '%' END
        UNION ALL 
        SELECT 
             B.COMP_NO 
           , B.DOCCTG_ID
           , B.P_DOCCTG_ID
           , C.LVL+ 1
		   , B.DESCRIPTION
		   , CONVERT(VARCHAR, C.SORT + '-' + CONVERT(VARCHAR, B.DOCCTG_ID)) AS SORT
        FROM TADOCCTG B INNER JOIN DATATABLE C  ON B.COMP_NO = C.COMP_NO AND B.DOCCTG_ID = C.P_DOCCTG_ID AND B.COMP_NO= @PCOMP_NO
        WHERE 1=1
    ) 
    SELECT TOP (SELECT COUNT(*) FROM DATATABLE) * FROM DATATABLE
	ORDER BY SORT
)