CREATE FUNCTION [dbo].[SFAEQCTGASMB_ALL]
(
      @PCOMP_NO NVARCHAR(40)
    , @P_EQ_CTG_ASMB_ID BIGINT
)
RETURNS TABLE 
AS
RETURN(
    WITH DATATABLE AS ( 
        SELECT 
             A.COMP_NO 
           , A.EQ_CTG_ASMB_ID
           , A.P_EQ_CTG_ASMB_ID
           , 1 AS LVL
           , A.DESCRIPTION
		   , CONVERT(VARCHAR, A.EQ_CTG_ASMB_ID) AS SORT
        FROM TAEQCTGASMB A
        WHERE 1=1
            and COMP_NO  = @PCOMP_NO
			and P_EQ_CTG_ASMB_ID = @P_EQ_CTG_ASMB_ID
        UNION ALL 
        SELECT 
             B.COMP_NO 
           , B.EQ_CTG_ASMB_ID
           , B.P_EQ_CTG_ASMB_ID
           , C.LVL+ 1
           , B.DESCRIPTION
		   , CONVERT(VARCHAR, C.SORT + '-' + CONVERT(VARCHAR, B.EQ_CTG_ASMB_ID)) AS SORT
        FROM TAEQCTGASMB B INNER JOIN DATATABLE C  ON B.COMP_NO = C.COMP_NO AND B.P_EQ_CTG_ASMB_ID = C.EQ_CTG_ASMB_ID AND B.COMP_NO= @PCOMP_NO
        WHERE 1=1
    ) 
    SELECT TOP (SELECT COUNT(*) FROM DATATABLE) * FROM DATATABLE
	ORDER BY SORT
)