CREATE FUNCTION [dbo].[SFAEQCTGASMB_PALL]
(
      @PCOMP_NO NVARCHAR(40)
    , @EQ_CTG_ASMB_ID BIGINT
	, @DESCRIPTION NVARCHAR(40)
)
RETURNS TABLE 
AS
RETURN(
    WITH DATATABLE AS ( 
        SELECT 
             A.COMP_NO 
           , A.EQ_CTG_ASMB_ID
           , A.P_EQ_CTG_ASMB_ID
           , 1 AS LVL
           , A.DESCRIPTION
		   , CONVERT(VARCHAR, A.EQ_CTG_ASMB_ID) AS SORT
        FROM TAEQCTGASMB A
        WHERE 1=1
            and COMP_NO  = @PCOMP_NO
			and EQ_CTG_ASMB_ID = CASE @EQ_CTG_ASMB_ID WHEN '' THEN EQ_CTG_ASMB_ID ELSE @EQ_CTG_ASMB_ID END
			and upper(DESCRIPTION) like CASE @EQ_CTG_ASMB_ID WHEN '' THEN '%'+upper(@DESCRIPTION)+'%' ELSE upper(DESCRIPTION) END
        UNION ALL 
        SELECT 
             B.COMP_NO 
           , B.EQ_CTG_ASMB_ID
           , B.P_EQ_CTG_ASMB_ID
           , C.LVL+ 1
           , B.DESCRIPTION
		   , CONVERT(VARCHAR, C.SORT + '-' + CONVERT(VARCHAR, B.EQ_CTG_ASMB_ID)) AS SORT
        FROM TAEQCTGASMB B INNER JOIN DATATABLE C  ON B.COMP_NO = C.COMP_NO AND B.EQ_CTG_ASMB_ID = C.P_EQ_CTG_ASMB_ID AND B.COMP_NO= @PCOMP_NO
        WHERE 1=1
    ) 
    SELECT TOP (SELECT COUNT(*) FROM DATATABLE) * FROM DATATABLE
	ORDER BY SORT
)

-- 2018.08.10 김영주추가. ISNULL 추가
ALTER FUNCTION [dbo].[SFAEQCTGASMB_PALL]
(
      @PCOMP_NO NVARCHAR(40)
    , @EQ_CTG_ASMB_ID BIGINT
	, @DESCRIPTION NVARCHAR(40)
)
RETURNS TABLE 
AS
RETURN(
    WITH DATATABLE AS ( 
        SELECT 
             A.COMP_NO 
           , A.EQ_CTG_ASMB_ID
           , A.P_EQ_CTG_ASMB_ID
           , 1 AS LVL
           , A.DESCRIPTION
		   , CONVERT(VARCHAR, A.EQ_CTG_ASMB_ID) AS SORT
        FROM TAEQCTGASMB A
        WHERE 1=1
            and COMP_NO  = @PCOMP_NO
			and EQ_CTG_ASMB_ID = CASE @EQ_CTG_ASMB_ID WHEN '' THEN EQ_CTG_ASMB_ID ELSE @EQ_CTG_ASMB_ID END
			and ISNULL(upper(DESCRIPTION),'') like CASE @EQ_CTG_ASMB_ID WHEN '' THEN '%'+upper(@DESCRIPTION)+'%' ELSE ISNULL(upper(DESCRIPTION),'') END
        UNION ALL 
        SELECT 
             B.COMP_NO 
           , B.EQ_CTG_ASMB_ID
           , B.P_EQ_CTG_ASMB_ID
           , C.LVL+ 1
           , B.DESCRIPTION
		   , CONVERT(VARCHAR, C.SORT + '-' + CONVERT(VARCHAR, B.EQ_CTG_ASMB_ID)) AS SORT
        FROM TAEQCTGASMB B INNER JOIN DATATABLE C  ON B.COMP_NO = C.COMP_NO AND B.EQ_CTG_ASMB_ID = C.P_EQ_CTG_ASMB_ID AND B.COMP_NO= @PCOMP_NO
        WHERE 1=1
    ) 
    SELECT TOP (SELECT COUNT(*) FROM DATATABLE) * FROM DATATABLE
	ORDER BY SORT
)