CREATE   FUNCTION [dbo].[SFAPLANTTODESC](
     @pCompNo VARCHAR(6)
    ,@pPlant NVARCHAR(12)
)

RETURNS NVARCHAR(480)

BEGIN

   DECLARE @DESCRIPTION AS NVARCHAR(200);

   SELECT @DESCRIPTION = description
   FROM TAPLANT
   WHERE COMP_NO = @pCompNo
       AND PLANT = @pPlant
   ;
   
   RETURN @DESCRIPTION
   
END;
